id: '8453'
lzid: '184'
code: base
name: Base
logo: https://github.com/helix-bridge/helixconf/blob/main/assets/chains/base.png?raw=true
rpcs:
  - https://mainnet.base.org
  - https://base-mainnet.g.alchemy.com/v2/$ALCHEMY_KEY
  - https://rpc.ankr.com/base/$ANKR_KEY
  - https://base-mainnet.blastapi.io/$BLAST_KEY
protocol:
  lnv2-default: '0x94C614DAeFDbf151E1BB53d6A201ae5fF56A9337'
  lnv2-opposite: null
  lnv3: '0xbA5D580B18b6436411562981e02c8A9aA1776D10'
messagers:
  - name: layerzero
    address: '0x61B6B8c7C00aA7F060a2BEDeE6b11927CC9c3eF1'
indexers:
  - type: hyperindex
    endpoint: https://indexer.bigdevenergy.link/e5a45aa/v1/graphql
tokens:
  - symbol: ETH
    address: '0x0000000000000000000000000000000000000000'
    decimals: 18
    type: native
  - symbol: USDC
    address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'
    decimals: 6
    type: erc20

couples:
  # eth
  - chain: arbitrum
    symbol: ETH
    protocol: lnv3
    fee: '10000000000000'
    messager: layerzero
  - chain: op
    symbol: ETH
    protocol: lnv3
    fee: '10000000000000'
    messager: layerzero
  - chain: scroll
    symbol: ETH
    protocol: lnv3
    fee: '10000000000000'
    messager: layerzero

  ## usdc
  - chain: bsc
    symbol: USDC
    protocol: lnv2-default
    fee: '100000'
    messager: layerzero
  - chain: arbitrum
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: gnosis
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: bsc
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: scroll
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: polygon
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: op
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: mantle
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
  - chain: avalanche
    symbol: USDC
    protocol: lnv3
    fee: '200000'
    messager: layerzero
