id: 8453
code: base
name: base
rpcs:
  - https://mainnet.base.org
tokens:
  - symbol: 'usdc'
    address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'
    decimals: 6

couples:
  - chain: bsc
    symbol: usdc
    protocol: lnv2-default
    fee: '100000'
    messager: layerzero
