name: Check code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Check build:ts
        run: npm run build:ts

      - name: Check test:ts
        run: npm run test:ts
