name: 'Publish'

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:


jobs:

  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Deps
        run: npm i

      - name: Build template
        run: npm run build:ts

      - name: Publish ts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd generated/typescript
          npm run release

